### ISSUE TITLE
Bot seems to die after a day, not sure if it's from lack of activity in stage or something different

### ISSUE THREAD

**Issue by Ufinexa** [parzival-space/discord-radio-bot#4]
```
node:events:505
      throw er; // Unhandled 'error' event
      ^
Error: 1001:
    at WebSocket.<anonymous> (/home/ufinexa/UfiRadio/node_modules/eris/lib/voice/VoiceConnection.js:348:55)
    at WebSocket.emit (node:events:527:28)
    at WebSocket.emitClose (/home/ufinexa/UfiRadio/node_modules/ws/lib/websocket.js:246:10)
    at TLSSocket.socketOnClose (/home/ufinexa/UfiRadio/node_modules/ws/lib/websocket.js:1148:15)
    at TLSSocket.emit (node:events:539:35)
    at node:net:715:12
    at TCP.done (node:_tls_wrap:581:7)
Emitted 'error' event on VoiceConnection instance at:
    at VoiceConnection.disconnect (/home/ufinexa/UfiRadio/node_modules/eris/lib/voice/VoiceConnection.js:432:22)
    at WebSocket.<anonymous> (/home/ufinexa/UfiRadio/node_modules/eris/lib/voice/VoiceConnection.js:365:22)
    at WebSocket.emit (node:events:527:28)
    [... lines matching original stack trace ...]
    at TCP.done (node:_tls_wrap:581:7)
```
This is what I have had when leaving the bot to do it's own thing, usually lasts about a day, few hours minimum before this pops up

**Comment by parzival-space** [comment]
I cannot reproduce this problem after running the bot for about 17 hours.
This may be caused by some kind of network issues that cause the bot to lose connection.

Maybe it is possible to add something like a automatic reconnect feature....
I will try to implement this and get back to you as soon as possible.

If you are using Docker to deploy the bot, you can try to start the bot with the following command:
```bash
docker run -d --name my-cool-radio-bot --restart=always discord-radio-bot
```
This should cause the bot to automatically restart on crashes.
The docker-compose file should already do this.

**Comment by Ufinexa** [comment]
Understood, I am running this on an OVH server based in France, funnily enough it has been running perfectly for me too now for around the same duration you just mentioned in your testing, so maybe it was just a blip with the server or even the stream itself, but it did happen around 3 times before I made this issue. Hoping it sticks this time! 

I use the npm way of running it, but I might switch to docker to get it to reboot in that way. Thank you so much again!
